DROP TABLE IF EXISTS TB_ADMIN;
DROP TABLE IF EXISTS TB_ADMIN_ACCOUNT;
DROP TABLE IF EXISTS TB_ADMIN_CERT;
DROP TABLE IF EXISTS TB_ADMIN_ROLE;
DROP TABLE IF EXISTS TB_ROLE;
DROP TABLE IF EXISTS TB_CUBE_CONFIG;
DROP TABLE IF EXISTS TB_ADMIN_LOG;
DROP TABLE IF EXISTS TB_ADMIN_LOG_BACKUP;
DROP TABLE IF EXISTS TB_BACKLOG_TASK;

CREATE TABLE TB_ADMIN (
  ADMINID varchar(32) NOT NULL COMMENT '主键id',
  TRUENAME varchar(50) DEFAULT NULL COMMENT '姓名',
  MOBILE varchar(20) DEFAULT NULL COMMENT '手机号',
  MAIL varchar(50) DEFAULT NULL COMMENT '邮箱',
  STATUS varchar(1) NOT NULL DEFAULT '0' COMMENT '管理员状态   0：启用     1：停用',
  CREATEOPERATOR varchar(32) DEFAULT NULL COMMENT '创建人id',
  CREATETIME datetime DEFAULT NULL COMMENT '创建时间',
  LASTOPERATOR varchar(32) DEFAULT NULL COMMENT '最后操作人id',
  LASTTIME datetime DEFAULT NULL COMMENT '最后操作时间',
  PRIMARY KEY (ADMINID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TB_ADMIN_ACCOUNT (
  `ACCOUNTID` VARCHAR(32) NOT NULL COMMENT '主键ID',
  `ADMINID` VARCHAR(32) DEFAULT NULL COMMENT '管理员ID',
  `ACCOUNT` VARCHAR(50) DEFAULT NULL COMMENT '账号',
  `PASSWORD` VARCHAR(50) DEFAULT NULL COMMENT '密码',
  `PASSWORDSTATUS` VARCHAR(1) DEFAULT NULL COMMENT '密码修改状态  0：未修改 1：已修改',
  `CREATETIME` DATETIME DEFAULT NULL COMMENT '录入时间',
  `CREATEOPERATOR` VARCHAR(32) DEFAULT NULL COMMENT '录入人ID',
  PRIMARY KEY (`ACCOUNTID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE TB_ADMIN_CERT (
  CERTID varchar(32) NOT NULL COMMENT '主键id',
  ADMINID varchar(32) DEFAULT NULL COMMENT '管理员id',
  CERTENTITY varchar(2000) DEFAULT NULL COMMENT '证书base64编码',
  SUBJECT varchar(255) DEFAULT NULL COMMENT '证书主题',
  ISSUER varchar(255) DEFAULT NULL COMMENT '证书颁发者',
  CERTIDENTIFIER varchar(255) DEFAULT NULL,
  CREATEOPERATOR varchar(32) DEFAULT NULL COMMENT '录入人id',
  CREATETIME datetime DEFAULT NULL COMMENT '录入时间',
  LASTOPERATOR varchar(32) DEFAULT NULL COMMENT '修改人id',
  LASTTIME datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (CERTID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TB_ADMIN_ROLE (
  ID varchar(32) NOT NULL COMMENT '主键id',
  ADMINID varchar(32) DEFAULT NULL COMMENT '系统管理员id',
  ROLEID varchar(32) DEFAULT NULL COMMENT '角色id',
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TB_ROLE (
  ROLEID varchar(32) NOT NULL COMMENT '主键id',
  ROLENAME varchar(20) DEFAULT NULL COMMENT '角色名称',
  ROLEDESC varchar(100) DEFAULT NULL COMMENT '角色描述',
  ISDEFAULT varchar(1) DEFAULT '1' COMMENT '是否默认  0：是   1：不是',
  EDITABLE varchar(1) DEFAULT '1' COMMENT '是否可编辑   0：是   1：不是',
  CREATEUSERID varchar(32) DEFAULT NULL COMMENT '创建人',
  CREATEDATE datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (ROLEID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TB_CUBE_CONFIG (
  ID int(11) NOT NULL AUTO_INCREMENT,
  SERVICE_ID varchar(64) DEFAULT NULL,
  NAME varchar(100) DEFAULT NULL,
  VALUE longtext,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

CREATE TABLE TB_ADMIN_LOG (
  ID int(20) NOT NULL AUTO_INCREMENT,
  OPERATOR varchar(200) DEFAULT NULL,
  CLIENTIP varchar(200) DEFAULT NULL,
  OPERATIONTYPE varchar(200) DEFAULT NULL,
  OPTCONTENT varchar(200) DEFAULT NULL,
  OPTTIME datetime DEFAULT NULL,
  OPTRESULT varchar(200) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;

CREATE TABLE TB_ADMIN_LOG_BACKUP (
  ID int(20) NOT NULL AUTO_INCREMENT,
  OPERATOR varchar(200) DEFAULT NULL,
  CLIENTIP varchar(200) DEFAULT NULL,
  OPERATIONTYPE varchar(200) DEFAULT NULL,
  OPTCONTENT varchar(200) DEFAULT NULL,
  OPTTIME datetime DEFAULT NULL,
  OPTRESULT varchar(200) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;

CREATE TABLE TB_BACKLOG_TASK (
  TASKID varchar(32) NOT NULL COMMENT '任务主键id',
  TASKNAME varchar(30) DEFAULT NULL COMMENT '任务名称',
  TABLENAME varchar(30) DEFAULT NULL COMMENT '日志表-名称',
  TASKSTATUS varchar(1) DEFAULT NULL COMMENT '任务执行状态    0：执行中   1：闲置',
  TASKRESULT varchar(1) DEFAULT NULL COMMENT '任务上次执行结果   0：成功   1：失败',
  ERRORMSG text COMMENT '发生异常时的错误信息',
  STARTTIME datetime DEFAULT NULL COMMENT '（上次）开始执行时间',
  ENDTIME datetime DEFAULT NULL COMMENT '执行（上次）结束时间',
  NEXTFIRETIME datetime DEFAULT NULL COMMENT '任务下次执行时间',
  LOCALFILEDOWNLOADPATH varchar(500) DEFAULT NULL COMMENT '手动归档操作-本地归档类型-归档文件下载路径',
  CREATETIME datetime DEFAULT NULL COMMENT '任务创建时间',
  OPERATETIME datetime DEFAULT NULL COMMENT '任务操作时间',
  PRIMARY KEY (TASKID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;